//! Gradle project-model provider using an injected init script.

use std::path::{Path, PathBuf};

use serde::Deserialize;

use super::fingerprint::collect_build_files;
use super::model::{
    Module, ModuleId, ModuleOutput, ProjectModel, ProviderKind, SourceRoot, SourceRootKind,
};
use super::provider::{ProbeError, ProjectProvider};
use super::runner::{Command, CommandRunner, GRADLE};

const PROBE_VERSION: &str = "5";
const SENTINEL: &str = "KRUSTY_MODEL_JSON ";
const TASK: &str = "krustyModel";
const MAX_FAILURE_DETAILS: usize = 8;

/// Printed by the init script, one line per Gradle project.
///
/// `artifactView { lenient = true }` is what keeps a single unresolvable dependency from failing the
/// whole sync — without it one typo in one module leaves the editor with no classpath at all.
const INIT_SCRIPT: &str = r#"// Generated by krusty-lsp. Injected with -I; the project is not modified.
allprojects { project ->
    project.tasks.register("krustyModel") {
        doLast {
            def lenient = { configuration ->
                configuration == null ? [] :
                    configuration.incoming.artifactView { view -> view.lenient = true }
                        .files.collect { it.absolutePath }
            }

            // Plain Kotlin/JVM and Java: the SourceSetContainer. Absent for multiplatform.
            def sourceSets = []
            project.extensions.findByName("sourceSets")?.each { set ->
                def roots = [] as Set
                set.allJava?.srcDirs?.each { roots << it.absolutePath }
                try {
                    set.extensions.findByName("kotlin")?.srcDirs?.each { roots << it.absolutePath }
                } catch (ignored) {
                }
                def compilerArgs = []
                try {
                    def compileTask = project.tasks.findByName(set.getCompileTaskName("kotlin"))
                    compilerArgs = compileTask?.compilerOptions?.freeCompilerArgs?.getOrElse([]) ?: []
                } catch (ignored) {
                }
                sourceSets << [
                    name      : set.name,
                    roots     : roots.toList().sort(),
                    classpath : lenient(project.configurations.findByName(set.compileClasspathConfigurationName)),
                    output    : set.output?.classesDirs?.files?.collect { it.absolutePath } ?: [],
                    kotlincArgs: compilerArgs.collect { it.toString() },
                ]
            }

            // Kotlin Multiplatform: one entry per compilation (jvm/main, jvm/test, …). The natural
            // compilation unit carries both the union of its source sets' directories and the compile
            // classpath, which lives on the compilation rather than on any single source set.
            def kotlinCompilations = []
            try {
                def kotlin = project.extensions.findByName("kotlin")
                if (kotlin != null && project.plugins.hasPlugin("org.jetbrains.kotlin.multiplatform")) {
                    kotlin.targets.findAll { target -> target.platformType?.name == "jvm" }.each { target ->
                        target.compilations.each { compilation ->
                            def roots = [] as Set
                            compilation.allKotlinSourceSets.each { ss ->
                                ss.kotlin?.srcDirs?.each { roots << it.absolutePath }
                            }
                            try {
                                def javaSourceSet = project.extensions.findByName("sourceSets")
                                    ?.findByName(compilation.defaultSourceSet?.name)
                                javaSourceSet?.allJava?.srcDirs?.each { roots << it.absolutePath }
                            } catch (ignored) {
                            }
                            def associates = []
                            try { associates = compilation.associateWith.collect { it.output?.classesDirs?.files }.flatten().findAll { it != null }.collect { it.absolutePath } } catch (ignored) {}
                            def compilerArgs = []
                            try { compilerArgs = compilation.compileTaskProvider.get().compilerOptions?.freeCompilerArgs?.getOrElse([]) ?: [] } catch (ignored) {}
                            kotlinCompilations << [
                                target    : target.name,
                                name      : compilation.name,
                                platform  : target.platformType?.name,
                                roots     : roots.toList().sort(),
                                classpath : compilation.compileDependencyFiles?.collect { it.absolutePath } ?: [],
                                output    : compilation.output?.classesDirs?.files?.collect { it.absolutePath } ?: [],
                                isTest    : compilation.name.toLowerCase().contains("test"),
                                associates: associates,
                                jvmTarget : (target.platformType?.name == "jvm") ? (compilation.compilerOptions?.options?.jvmTarget?.getOrNull()?.target) : null,
                                kotlincArgs: compilerArgs.collect { it.toString() },
                            ]
                        }
                    }
                }
            } catch (ignored) {
            }

            // Android: one entry per variant, with the AGP compile classpath and the platform jar.
            def androidVariants = []
            try {
                def android = project.extensions.findByName("android")
                if (android != null) {
                    def boot = []
                    try { boot = android.bootClasspath.collect { it.absolutePath } } catch (ignored) {}
                    def variants = android.hasProperty("applicationVariants") ? android.applicationVariants :
                                   (android.hasProperty("libraryVariants") ? android.libraryVariants : [])
                    variants.each { variant ->
                        def roots = [] as Set
                        variant.sourceSets.each { ss ->
                            ss.javaDirectories?.each { roots << it.absolutePath }
                            try { ss.kotlinDirectories?.each { roots << it.absolutePath } } catch (ignored) {}
                        }
                        def classpath = boot as List
                        try { classpath = classpath + variant.getCompileClasspath(null).files.collect { it.absolutePath } } catch (ignored) {}
                        def output = []
                        try { output = variant.javaCompileProvider.get().destinationDirectory.get().asFile.absolutePath } catch (ignored) {}
                        def compilerArgs = []
                        try {
                            def taskName = "compile${variant.name.capitalize()}Kotlin"
                            def compileTask = project.tasks.findByName(taskName)
                            compilerArgs = compileTask?.compilerOptions?.freeCompilerArgs?.getOrElse([]) ?: []
                        } catch (ignored) {}
                        androidVariants << [
                            name      : variant.name,
                            roots     : roots.toList().sort(),
                            classpath : classpath.unique(),
                            output    : output ? [output] : [],
                            isTest    : variant.name.toLowerCase().contains("test"),
                            kotlincArgs: compilerArgs.collect { it.toString() },
                        ]
                    }
                }
            } catch (ignored) {
            }

            def kotlin = project.extensions.findByName("kotlin")
            def jvmTarget = null
            def kotlincArgs = []
            try {
                jvmTarget = kotlin?.compilerOptions?.jvmTarget?.getOrNull()?.target
                kotlincArgs.addAll(kotlin?.compilerOptions?.freeCompilerArgs?.getOrElse([]) ?: [])
            } catch (ignored) {
            }
            kotlincArgs = kotlincArgs.collect { it.toString() }.unique()
            def javaHome = null
            try {
                def java = project.extensions.findByType(org.gradle.api.plugins.JavaPluginExtension)
                javaHome = java?.toolchain?.installationPath?.getOrNull()?.asFile?.absolutePath
            } catch (ignored) {
            }
            def model = [
                path              : project.path,
                name              : project.name,
                projectDir        : project.projectDir.absolutePath,
                javaHome          : javaHome ?: System.getProperty("java.home"),
                jvmTarget         : jvmTarget,
                kotlincArgs       : kotlincArgs,
                sourceSets        : sourceSets,
                kotlinCompilations: kotlinCompilations,
                androidVariants   : androidVariants,
                projectDeps       : project.configurations.findAll { it.name == "implementation" || it.name == "api" }
                    .collectMany { configuration ->
                        configuration.dependencies
                            .findAll { it instanceof org.gradle.api.artifacts.ProjectDependency }
                            .collect { it.path ?: it.dependencyProject.path }
                    }.unique(),
            ]
            println "KRUSTY_MODEL_JSON " + groovy.json.JsonOutput.toJson(model)
        }
    }
}
"#;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct GradleProject {
    path: String,
    name: String,
    project_dir: String,
    #[serde(default)]
    java_home: Option<String>,
    #[serde(default)]
    jvm_target: Option<String>,
    #[serde(default)]
    kotlinc_args: Vec<String>,
    #[serde(default)]
    source_sets: Vec<GradleSourceSet>,
    #[serde(default)]
    kotlin_compilations: Vec<KotlinCompilation>,
    #[serde(default)]
    android_variants: Vec<AndroidVariant>,
    #[serde(default)]
    project_deps: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct GradleSourceSet {
    name: String,
    #[serde(default)]
    roots: Vec<String>,
    #[serde(default)]
    classpath: Vec<String>,
    #[serde(default)]
    output: Vec<String>,
    #[serde(default)]
    kotlinc_args: Vec<String>,
}

/// One Kotlin Multiplatform compilation, e.g. the `main` compilation of the `jvm` target.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct KotlinCompilation {
    target: String,
    name: String,
    platform: String,
    #[serde(default)]
    roots: Vec<String>,
    #[serde(default)]
    classpath: Vec<String>,
    #[serde(default)]
    output: Vec<String>,
    #[serde(default)]
    is_test: bool,
    /// Outputs whose `internal` declarations this compilation may see (`associateWith`).
    #[serde(default)]
    associates: Vec<String>,
    #[serde(default)]
    jvm_target: Option<String>,
    #[serde(default)]
    kotlinc_args: Vec<String>,
}

/// One Android build variant, e.g. `debug`.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct AndroidVariant {
    name: String,
    #[serde(default)]
    roots: Vec<String>,
    #[serde(default)]
    classpath: Vec<String>,
    #[serde(default)]
    output: Vec<String>,
    #[serde(default)]
    is_test: bool,
    #[serde(default)]
    kotlinc_args: Vec<String>,
}

#[derive(Debug)]
pub struct GradleProvider {
    root: PathBuf,
    gradle: PathBuf,
    init_script: PathBuf,
}

impl GradleProvider {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        let root = root.into();
        let gradle = GRADLE.resolve(&root);
        let init_script = init_script_path(&root);
        Self {
            root,
            gradle,
            init_script,
        }
    }

    pub fn build_files(&self) -> Vec<PathBuf> {
        collect_build_files(&self.root, 8, &is_gradle_build_file)
    }

    pub fn command(&self) -> Command {
        Command::new(self.gradle.clone(), self.root.clone()).args([
            "--quiet".to_string(),
            "--console=plain".to_string(),
            // Gradle's configuration cache rejects the probe's execution-time project access.
            "--no-configuration-cache".to_string(),
            "--init-script".to_string(),
            self.init_script.to_string_lossy().into_owned(),
            TASK.to_string(),
        ])
    }

    fn write_init_script(&self) -> Result<(), ProbeError> {
        if let Some(parent) = self.init_script.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|error| ProbeError::Io(format!("{}: {error}", parent.display())))?;
        }
        std::fs::write(&self.init_script, INIT_SCRIPT)
            .map_err(|error| ProbeError::Io(format!("{}: {error}", self.init_script.display())))
    }
}

impl ProjectProvider for GradleProvider {
    fn kind(&self) -> ProviderKind {
        ProviderKind::Gradle
    }

    fn root(&self) -> &Path {
        &self.root
    }

    fn watch_paths(&self) -> Vec<PathBuf> {
        self.build_files()
    }

    fn fingerprint_salt(&self) -> String {
        format!("gradle-{PROBE_VERSION}")
    }

    fn probe(&self, runner: &dyn CommandRunner) -> Result<ProjectModel, ProbeError> {
        self.write_init_script()?;
        let command = self.command();
        let output = runner
            .run(&command)
            .map_err(|error| ProbeError::Io(format!("{}: {error}", self.gradle.display())))?;
        if !output.succeeded() {
            return Err(ProbeError::Tool {
                program: self.gradle.to_string_lossy().into_owned(),
                status: output.status,
                message: gradle_failure_summary(&output.stderr, &output.stdout),
            });
        }
        parse_model(&self.root, &output.stdout)
    }
}

fn init_script_path(root: &Path) -> PathBuf {
    let mut hasher = super::fingerprint::Hasher::default();
    hasher.write_str(&root.to_string_lossy());
    std::env::temp_dir().join(format!(
        "krusty-gradle-{:016x}-v{PROBE_VERSION}.init.gradle",
        hasher.finish().as_u64()
    ))
}

fn is_gradle_build_file(path: &Path) -> bool {
    let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
        return false;
    };
    name.ends_with(".gradle")
        || name.ends_with(".gradle.kts")
        || name == "gradle.properties"
        || name == "libs.versions.toml"
        || name == "gradle-wrapper.properties"
        || name == "gradle.lockfile"
}

fn parse_model(root: &Path, stdout: &str) -> Result<ProjectModel, ProbeError> {
    let mut projects = Vec::new();
    for line in stdout.lines() {
        let Some(payload) = line.trim_start().strip_prefix(SENTINEL) else {
            continue;
        };
        let project: GradleProject = serde_json::from_str(payload)
            .map_err(|error| ProbeError::Parse(format!("{error} in `{payload}`")))?;
        projects.push(project);
    }
    if projects.is_empty() {
        return Err(ProbeError::Parse(
            "no project model lines in gradle output".to_string(),
        ));
    }

    let jdk_home = projects
        .iter()
        .find_map(|project| project.java_home.clone())
        .map(PathBuf::from);
    let mut modules = Vec::new();
    for project in &projects {
        // Android and multiplatform replace the plain source-set view: an Android project's JVM
        // sources are organised per variant, and a multiplatform project has no SourceSetContainer
        // at all. Prefer the richer view when the corresponding plugin reported one.
        if !project.android_variants.is_empty() {
            for variant in &project.android_variants {
                modules.push(android_module_of(project, variant));
            }
        } else if !project.kotlin_compilations.is_empty() {
            for compilation in project
                .kotlin_compilations
                .iter()
                .filter(|compilation| compilation.platform == "jvm")
            {
                modules.push(kmp_module_of(project, compilation));
            }
        } else {
            for source_set in &project.source_sets {
                modules.push(module_of(project, source_set));
            }
        }
    }
    Ok(ProjectModel {
        root: root.to_path_buf(),
        kind: ProviderKind::Gradle,
        jdk_home,
        modules,
    })
}

fn module_of(project: &GradleProject, source_set: &GradleSourceSet) -> Module {
    let kind = if is_test_source_set(&source_set.name) {
        SourceRootKind::Test
    } else {
        SourceRootKind::Source
    };
    let mut module = Module::new(
        ModuleId::new(&project.path, &source_set.name),
        &project.project_dir,
    );
    module.display_name = format!("{}:{}", project.name, source_set.name);
    module.source_roots = source_set
        .roots
        .iter()
        .map(|root| SourceRoot {
            path: PathBuf::from(root),
            kind,
            generated: false,
            package_prefix: String::new(),
        })
        .collect();
    module.classpath = source_set.classpath.iter().map(PathBuf::from).collect();
    module.outputs = source_set
        .output
        .iter()
        .map(ModuleOutput::classes)
        .collect();
    module.jvm_target = project.jvm_target.clone();
    module.kotlinc_args = merged_kotlinc_args(&project.kotlinc_args, &source_set.kotlinc_args);
    module.depends_on = project
        .project_deps
        .iter()
        .map(|path| ModuleId::new(path, "main"))
        .collect();

    // A test source set sees its own project's `main` output, including `internal` declarations:
    // that is Gradle's association, and the compiler needs it as a friend path.
    if kind == SourceRootKind::Test {
        let main = ModuleId::new(&project.path, "main");
        if !module.depends_on.contains(&main) {
            module.depends_on.push(main);
        }
        for output in project
            .source_sets
            .iter()
            .filter(|set| set.name == "main")
            .flat_map(|set| set.output.iter())
        {
            module.friend_paths.push(PathBuf::from(output));
        }
    }
    module
}

/// One Kotlin Multiplatform compilation becomes a module keyed `<target>/<compilation>`
/// (e.g. `jvm/main`), so `jvm/main` and `jvm/test` stay distinct compilation units.
fn kmp_module_of(project: &GradleProject, compilation: &KotlinCompilation) -> Module {
    let source_set = format!("{}/{}", compilation.target, compilation.name);
    let kind = if compilation.is_test {
        SourceRootKind::Test
    } else {
        SourceRootKind::Source
    };
    let mut module = Module::new(
        ModuleId::new(&project.path, &source_set),
        &project.project_dir,
    );
    module.display_name = format!("{}:{source_set}", project.name);
    module.source_roots = compilation
        .roots
        .iter()
        .map(|root| SourceRoot {
            path: PathBuf::from(root),
            kind,
            generated: false,
            package_prefix: String::new(),
        })
        .collect();
    module.classpath = compilation.classpath.iter().map(PathBuf::from).collect();
    module.outputs = compilation
        .output
        .iter()
        .map(ModuleOutput::classes)
        .collect();
    module.friend_paths = compilation.associates.iter().map(PathBuf::from).collect();
    module.jvm_target = compilation
        .jvm_target
        .clone()
        .or_else(|| project.jvm_target.clone());
    module.kotlinc_args = merged_kotlinc_args(&project.kotlinc_args, &compilation.kotlinc_args);
    module.depends_on = project
        .project_deps
        .iter()
        .map(|path| ModuleId::new(path, "main"))
        .collect();
    module
}

/// One Android variant becomes a module keyed by the variant name (`debug`, `release`). The AGP
/// compile classpath already includes the platform `android.jar` and the generated `R.jar`.
fn android_module_of(project: &GradleProject, variant: &AndroidVariant) -> Module {
    let kind = if variant.is_test {
        SourceRootKind::Test
    } else {
        SourceRootKind::Source
    };
    let mut module = Module::new(
        ModuleId::new(&project.path, &variant.name),
        &project.project_dir,
    );
    module.display_name = format!("{}:{}", project.name, variant.name);
    module.source_roots = variant
        .roots
        .iter()
        .map(|root| SourceRoot {
            path: PathBuf::from(root),
            kind,
            generated: false,
            package_prefix: String::new(),
        })
        .collect();
    module.classpath = variant.classpath.iter().map(PathBuf::from).collect();
    module.outputs = variant.output.iter().map(ModuleOutput::classes).collect();
    module.jvm_target = project.jvm_target.clone();
    module.kotlinc_args = merged_kotlinc_args(&project.kotlinc_args, &variant.kotlinc_args);
    module.depends_on = project
        .project_deps
        .iter()
        .map(|path| ModuleId::new(path, "main"))
        .collect();
    module
}

fn merged_kotlinc_args(project: &[String], compilation: &[String]) -> Vec<String> {
    let mut merged = Vec::new();
    for argument in project.iter().chain(compilation) {
        if !merged.contains(argument) {
            merged.push(argument.clone());
        }
    }
    merged
}

fn is_test_source_set(name: &str) -> bool {
    name == "test" || name.ends_with("Test") || name.ends_with("test")
}

fn gradle_failure_summary(stderr: &str, stdout: &str) -> String {
    gradle_failure_details(stderr)
        .or_else(|| gradle_failure_details(stdout))
        .unwrap_or_else(|| {
            stderr
                .lines()
                .chain(stdout.lines())
                .map(str::trim)
                .find(|line| !line.is_empty())
                .unwrap_or_default()
                .to_string()
        })
}

fn gradle_failure_details(output: &str) -> Option<String> {
    let mut lines = output.lines().map(str::trim_end);
    while let Some(line) = lines.next() {
        if line.trim() != "* What went wrong:" {
            continue;
        }
        let mut cause = Vec::new();
        let mut truncated = false;
        for detail in lines.by_ref() {
            let detail = detail.trim();
            if detail.is_empty() || detail.starts_with('*') {
                break;
            }
            let detail = detail.trim_start_matches('>').trim();
            if detail.is_empty() {
                continue;
            }
            if cause.len() == MAX_FAILURE_DETAILS {
                truncated = true;
                break;
            }
            cause.push(detail);
        }
        if !cause.is_empty() {
            let mut summary = cause.join(" — ");
            if truncated {
                summary.push_str(" — ...");
            }
            return Some(summary);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::project::runner::testing::FakeRunner;
    use crate::project::testing::TempTree;

    fn recorded_output() -> String {
        let core = r#"{"path":":core","name":"core","projectDir":"/p/core","javaHome":"/jdk21","jvmTarget":"21","kotlincArgs":["-Xcontext-parameters"],"sourceSets":[{"name":"main","roots":["/p/core/src/main/kotlin"],"classpath":["/m2/kotlin-stdlib.jar"],"output":["/p/core/build/classes/java/main","/p/core/build/classes/kotlin/main"],"kotlincArgs":["-Xname-based-destructuring=complete"]}],"projectDeps":[]}"#;
        let app = r#"{"path":":app","name":"app","projectDir":"/p/app","javaHome":"/jdk21","jvmTarget":"21","kotlincArgs":[],"sourceSets":[{"name":"main","roots":["/p/app/src/main/kotlin"],"classpath":["/m2/kotlin-stdlib.jar"],"output":["/p/app/build/classes/kotlin/main"]},{"name":"test","roots":["/p/app/src/test/kotlin"],"classpath":["/m2/junit.jar"],"output":["/p/app/build/classes/kotlin/test"]}],"projectDeps":[":core"]}"#;
        format!("Configuring project\n{SENTINEL}{core}\n{SENTINEL}{app}\nBUILD SUCCESSFUL\n")
    }

    #[test]
    fn the_probe_injects_an_init_script_and_never_edits_the_project() {
        let tree = TempTree::new("gradle-command");
        tree.write("settings.gradle.kts", "");
        tree.write("gradlew", "#!/bin/sh\n");
        let provider = GradleProvider::new(tree.root());
        let runner = FakeRunner::new(vec![FakeRunner::stdout(&recorded_output())]);

        provider.probe(&runner).unwrap();

        let command = runner.command(0);
        assert_eq!(command.program, tree.path("gradlew"));
        assert_eq!(command.working_directory, tree.root);
        assert_eq!(command.args[0], "--quiet");
        assert_eq!(command.args[1], "--console=plain");
        assert_eq!(command.args[2], "--no-configuration-cache");
        assert_eq!(command.args[3], "--init-script");
        assert_eq!(command.args[5], TASK);

        let script = std::fs::read_to_string(&command.args[4]).unwrap();
        assert!(script.contains("lenient = true"), "{script}");
        assert!(script.contains("compileTask?.compilerOptions"), "{script}");
        assert!(script.contains("set.allJava?.srcDirs"), "{script}");
        assert!(
            script.contains("set.extensions.findByName(\"kotlin\")?.srcDirs"),
            "{script}"
        );
        assert!(
            script.contains("compilation.defaultSourceSet?.name"),
            "{script}"
        );
        assert!(!script.contains("set.allSource?.srcDirs"), "{script}");
        assert!(!tree.path(".krusty").exists());
    }

    #[test]
    fn a_failure_summary_reports_gradles_what_went_wrong_not_the_banner() {
        let output = "\
FAILURE: Build completed with 11 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:krustyModel'.
> Could not resolve all dependencies for configuration ':app:compileClasspath'.
   > Could not find org.example:missing:1.0.

* Try:
> Run with --stacktrace option to get the stack trace.
";
        assert_eq!(
            gradle_failure_summary("", output),
            "Execution failed for task ':app:krustyModel'. — Could not resolve all dependencies \
             for configuration ':app:compileClasspath'. — Could not find org.example:missing:1.0."
        );
    }

    #[test]
    fn a_failure_without_the_expected_format_falls_back_to_the_first_line() {
        assert_eq!(
            gradle_failure_summary("gradle: command not found\n", ""),
            "gradle: command not found"
        );
    }

    #[test]
    fn a_failure_summary_bounds_the_cause_chain() {
        let details = (1..=10)
            .map(|index| format!("> cause {index}"))
            .collect::<Vec<_>>()
            .join("\n");
        let output = format!("* What went wrong:\n{details}\n\n* Try:\n");

        assert_eq!(
            gradle_failure_summary(&output, ""),
            "cause 1 — cause 2 — cause 3 — cause 4 — cause 5 — cause 6 — cause 7 — cause 8 — ..."
        );
    }

    #[test]
    fn recorded_output_becomes_one_module_per_source_set() {
        let model = parse_model(Path::new("/p"), &recorded_output()).unwrap();
        assert_eq!(model.kind, ProviderKind::Gradle);
        assert_eq!(model.jdk_home, Some(PathBuf::from("/jdk21")));

        let core = model.module(&ModuleId::new(":core", "main")).unwrap();
        assert_eq!(core.classpath, vec![PathBuf::from("/m2/kotlin-stdlib.jar")]);
        assert_eq!(
            core.outputs,
            vec![
                ModuleOutput::classes("/p/core/build/classes/java/main"),
                ModuleOutput::classes("/p/core/build/classes/kotlin/main"),
            ]
        );
        assert_eq!(core.jvm_target.as_deref(), Some("21"));
        assert_eq!(
            core.kotlinc_args,
            vec![
                "-Xcontext-parameters".to_string(),
                "-Xname-based-destructuring=complete".to_string(),
            ]
        );

        let app = model.module(&ModuleId::new(":app", "main")).unwrap();
        assert_eq!(app.depends_on, vec![ModuleId::new(":core", "main")]);
        assert_eq!(
            model.compile_classpath(app),
            vec![
                PathBuf::from("/m2/kotlin-stdlib.jar"),
                PathBuf::from("/p/core/build/classes/java/main"),
                PathBuf::from("/p/core/build/classes/kotlin/main"),
            ]
        );
    }

    #[test]
    fn a_test_source_set_gets_its_main_output_as_a_friend_path() {
        let model = parse_model(Path::new("/p"), &recorded_output()).unwrap();
        let test = model.module(&ModuleId::new(":app", "test")).unwrap();
        assert_eq!(test.source_roots[0].kind, SourceRootKind::Test);
        assert_eq!(
            test.friend_paths,
            vec![PathBuf::from("/p/app/build/classes/kotlin/main")]
        );
        assert!(test.depends_on.contains(&ModuleId::new(":app", "main")));
    }

    #[test]
    fn a_failing_build_reports_the_tool_error_instead_of_an_empty_model() {
        let tree = TempTree::new("gradle-failure");
        let runner = FakeRunner::new(vec![FakeRunner::failure(
            1,
            "\nFAILURE: Could not resolve org.example:missing:1.0\n",
        )]);
        let error = GradleProvider::new(tree.root()).probe(&runner).unwrap_err();
        assert_eq!(
            error.to_string(),
            "gradle exited with 1: FAILURE: Could not resolve org.example:missing:1.0"
        );
    }

    #[test]
    fn output_without_model_lines_is_a_parse_error() {
        let error = parse_model(Path::new("/p"), "BUILD SUCCESSFUL\n").unwrap_err();
        assert!(matches!(error, ProbeError::Parse(_)), "{error:?}");
    }

    #[test]
    fn a_multiplatform_project_includes_only_jvm_compilations() {
        let shared = concat!(
            r#"{"path":":shared","name":"shared","projectDir":"/p/shared","javaHome":"/jdk21","jvmTarget":null,"kotlincArgs":[],"sourceSets":[],"kotlinCompilations":["#,
            r#"{"target":"jvm","name":"main","platform":"jvm","roots":["/p/shared/src/commonMain/kotlin","/p/shared/src/jvmMain/java","/p/shared/src/jvmMain/kotlin"],"classpath":["/m2/kotlin-stdlib.jar"],"output":["/p/shared/build/classes/kotlin/jvm/main"],"isTest":false,"associates":[],"jvmTarget":"17","kotlincArgs":["-XXLanguage:+ContextParameters"]},"#,
            r#"{"target":"jvm","name":"test","platform":"jvm","roots":["/p/shared/src/jvmTest/kotlin"],"classpath":["/m2/kotlin-test.jar"],"output":["/p/shared/build/classes/kotlin/jvm/test"],"isTest":true,"associates":["/p/shared/build/classes/kotlin/jvm/main"],"jvmTarget":"17"},"#,
            r#"{"target":"linuxX64","name":"main","platform":"native","roots":["/p/shared/src/linuxMain/kotlin"],"classpath":["/m2/native.klib"],"output":["/p/shared/build/classes/kotlin/linux/main"],"isTest":false,"associates":[],"jvmTarget":null}"#,
            r#"],"androidVariants":[],"projectDeps":[]}"#,
        );
        let output = format!("{SENTINEL}{shared}\n");
        let model = parse_model(Path::new("/p"), &output).unwrap();

        let main = model.module(&ModuleId::new(":shared", "jvm/main")).unwrap();
        assert_eq!(main.source_roots.len(), 3);
        assert!(main
            .source_roots
            .iter()
            .any(|root| root.path == Path::new("/p/shared/src/jvmMain/java")));
        assert_eq!(main.jvm_target.as_deref(), Some("17"));
        assert_eq!(
            main.outputs,
            vec![ModuleOutput::classes(
                "/p/shared/build/classes/kotlin/jvm/main"
            )]
        );
        assert_eq!(
            main.kotlinc_args,
            vec!["-XXLanguage:+ContextParameters".to_string()]
        );

        let test = model.module(&ModuleId::new(":shared", "jvm/test")).unwrap();
        assert_eq!(test.source_roots[0].kind, SourceRootKind::Test);
        assert_eq!(
            test.friend_paths,
            vec![PathBuf::from("/p/shared/build/classes/kotlin/jvm/main")]
        );
        assert!(model
            .module(&ModuleId::new(":shared", "linuxX64/main"))
            .is_none());
    }

    #[test]
    fn an_android_project_becomes_one_module_per_variant_with_the_platform_jar() {
        let app = concat!(
            r#"{"path":":app","name":"app","projectDir":"/p/app","javaHome":"/jdk17","jvmTarget":"1.8","kotlincArgs":["-XXLanguage:+ProjectFeature"],"sourceSets":[],"kotlinCompilations":[],"androidVariants":["#,
            r#"{"name":"debug","roots":["/p/app/src/main/kotlin","/p/app/src/debug/kotlin"],"classpath":["/sdk/platforms/android-34/android.jar","/p/app/build/generated/R.jar","/m2/appcompat.jar"],"output":["/p/app/build/tmp/kotlin-classes/debug"],"isTest":false,"kotlincArgs":["-XXLanguage:+DebugFeature"]},"#,
            r#"{"name":"release","roots":["/p/app/src/main/kotlin"],"classpath":["/sdk/platforms/android-34/android.jar"],"output":["/p/app/build/tmp/kotlin-classes/release"],"isTest":false}"#,
            r#"],"projectDeps":[]}"#,
        );
        let output = format!("{SENTINEL}{app}\n");
        let model = parse_model(Path::new("/p"), &output).unwrap();

        assert!(model.module(&ModuleId::new(":app", "main")).is_none());
        let debug = model.module(&ModuleId::new(":app", "debug")).unwrap();
        assert_eq!(debug.source_roots.len(), 2);
        assert!(debug
            .classpath
            .contains(&PathBuf::from("/sdk/platforms/android-34/android.jar")));
        assert!(debug
            .classpath
            .contains(&PathBuf::from("/p/app/build/generated/R.jar")));
        assert_eq!(debug.jvm_target.as_deref(), Some("1.8"));
        assert_eq!(
            debug.kotlinc_args,
            vec![
                "-XXLanguage:+ProjectFeature".to_string(),
                "-XXLanguage:+DebugFeature".to_string(),
            ]
        );
        let release = model.module(&ModuleId::new(":app", "release")).unwrap();
        assert_eq!(
            release.kotlinc_args,
            vec!["-XXLanguage:+ProjectFeature".to_string()]
        );
    }

    #[test]
    fn android_takes_precedence_over_plain_source_sets_in_a_kotlin_android_project() {
        // A kotlin-android project reports BOTH a source-set container and variants; the variants win.
        let app = concat!(
            r#"{"path":":app","name":"app","projectDir":"/p/app","javaHome":"/jdk17","jvmTarget":null,"kotlincArgs":[],"#,
            r#""sourceSets":[{"name":"main","roots":["/p/app/src/main/java"],"classpath":[],"output":[]}],"#,
            r#""kotlinCompilations":[],"#,
            r#""androidVariants":[{"name":"debug","roots":["/p/app/src/main/kotlin"],"classpath":["/sdk/android.jar"],"output":[],"isTest":false}],"#,
            r#""projectDeps":[]}"#,
        );
        let output = format!("{SENTINEL}{app}\n");
        let model = parse_model(Path::new("/p"), &output).unwrap();
        assert!(model.module(&ModuleId::new(":app", "debug")).is_some());
        assert!(model.module(&ModuleId::new(":app", "main")).is_none());
    }

    #[test]
    fn watched_files_cover_catalogs_wrappers_and_convention_plugins() {
        let tree = TempTree::new("gradle-watch");
        tree.write("settings.gradle.kts", "");
        tree.write("app/build.gradle", "");
        tree.write("gradle/libs.versions.toml", "");
        tree.write("gradle/wrapper/gradle-wrapper.properties", "");
        tree.write("buildSrc/src/main/kotlin/conventions.gradle.kts", "");
        tree.write("app/build/tmp/stale.gradle", "");
        tree.write("app/src/main/kotlin/App.kt", "");

        let watched = GradleProvider::new(tree.root()).watch_paths();
        assert_eq!(
            watched,
            vec![
                tree.path("app/build.gradle"),
                tree.path("buildSrc/src/main/kotlin/conventions.gradle.kts"),
                tree.path("gradle/libs.versions.toml"),
                tree.path("gradle/wrapper/gradle-wrapper.properties"),
                tree.path("settings.gradle.kts"),
            ]
        );
    }
}
