//! Prebuild the native runtime.
//!
//! krusty emits no C: a user's program is lowered to machine code by krusty's own code generator and
//! linked by krusty's own linker. The runtime that program links against — allocator, collector,
//! object model, syscalls, `_start` — is written in freestanding C under `src/native/runtime/`, and
//! this script compiles it **once, here, when krusty itself is built**, for every supported target,
//! so that the objects can be embedded in the compiler and a user's build needs nothing but krusty.
//! That is exactly how Go ships its runtime: compiled by the toolchain into archives that travel
//! with the distribution, never rebuilt by the user.
//!
//! The one consequence is that building *krusty* needs a C cross-compiler. `clang` targets every
//! architecture from one host with no sysroot, because the runtime is freestanding (see
//! `docs/BUILD_AND_NATIVE_PLAN.md`, *Requirement: every target buildable from any host*). When no
//! clang is available, krusty still builds — with no prebuilt runtime, the native backend reports
//! that plainly instead of failing somewhere inside a link.

use std::path::{Path, PathBuf};
use std::process::Command;

/// `(Arch variant name, LLVM triple, extra flags)` for every target the runtime supports.
///
/// `-fno-pic` and a small code model keep the objects free of GOT/PLT machinery: the output is a
/// static executable at a fixed address, so absolute 32-bit relocations are fine and simplest.
/// RISC-V's clang does not take `-mcmodel=small` (its equivalent is the default `medlow`).
const TARGETS: &[(&str, &str, &[&str])] = &[
    ("X86_64", "x86_64-unknown-linux-gnu", &["-mcmodel=small"]),
    ("Aarch64", "aarch64-unknown-linux-gnu", &["-mcmodel=small"]),
    ("Riscv64", "riscv64-unknown-linux-gnu", &[]),
];

const SOURCES: &[&str] = &["krusty_fp.c", "krusty_gc.c", "krusty_start.c"];
const HEADERS: &[&str] = &["krusty_sys.h", "krusty_rt.h"];

fn main() {
    let runtime_dir = Path::new("src/native/runtime");
    for file in SOURCES.iter().chain(HEADERS) {
        println!(
            "cargo:rerun-if-changed={}",
            runtime_dir.join(file).display()
        );
    }
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=KRUSTY_RUNTIME_CC");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let compiler = std::env::var("KRUSTY_RUNTIME_CC").unwrap_or_else(|_| "clang".to_string());

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs: the native runtime, prebuilt per target.\n");
    generated.push_str("pub const PREBUILT: &[(crate::native::Arch, &[(&str, &[u8])])] = &[\n");

    let mut built_any = false;
    for (arch, triple, extra) in TARGETS {
        let target_dir = out_dir.join("runtime").join(arch);
        std::fs::create_dir_all(&target_dir).expect("create runtime output directory");
        let mut objects = Vec::new();
        let mut ok = true;
        for source in SOURCES {
            let object = target_dir.join(source.replace(".c", ".o"));
            let status = Command::new(&compiler)
                .arg(format!("--target={triple}"))
                .args([
                    "-std=c11",
                    "-ffreestanding",
                    "-nostdlib",
                    "-fno-pic",
                    "-O2",
                    "-c",
                ])
                .args(*extra)
                .arg("-I")
                .arg(runtime_dir)
                .arg("-o")
                .arg(&object)
                .arg(runtime_dir.join(source))
                .status();
            match status {
                Ok(status) if status.success() => objects.push(object),
                Ok(status) => {
                    println!(
                        "cargo:warning=native runtime: `{compiler}` failed for {triple} on {source} ({status}); \
                         the {arch} target will be unavailable"
                    );
                    ok = false;
                    break;
                }
                Err(error) => {
                    println!(
                        "cargo:warning=native runtime: cannot run `{compiler}` ({error}); no native target \
                         will be available. Install clang, or set KRUSTY_RUNTIME_CC."
                    );
                    ok = false;
                    break;
                }
            }
        }
        if !ok {
            continue;
        }
        built_any = true;
        generated.push_str(&format!("    (crate::native::Arch::{arch}, &[\n"));
        for object in &objects {
            let name = object.file_name().unwrap().to_string_lossy();
            generated.push_str(&format!(
                "        ({name:?}, include_bytes!({:?})),\n",
                object.display().to_string()
            ));
        }
        generated.push_str("    ]),\n");
    }
    generated.push_str("];\n");
    generated.push_str(&format!(
        "/// Whether any target's runtime was prebuilt (a C compiler was available when krusty was built).\n\
         pub const AVAILABLE: bool = {built_any};\n"
    ));
    std::fs::write(out_dir.join("prebuilt_runtime.rs"), generated)
        .expect("write prebuilt_runtime.rs");
}
