//! Prebuild the native runtime.
//!
//! krusty emits no C: a user's program is lowered to machine code by krusty's own code generator and
//! linked by krusty's own linker. The runtime that program links against — allocator, collector,
//! object model, syscalls, `_start` — is written in freestanding C under `src/native/runtime/`, and
//! this script compiles it **once, here, when krusty itself is built**, for every supported target,
//! so that the objects can be embedded in the compiler and a user's build needs nothing but krusty.
//! That is exactly how Go ships its runtime: compiled by the toolchain into archives that travel
//! with the distribution, never rebuilt by the user.
//!
//! The one consequence is that building *krusty* needs a C cross-compiler. `clang` targets every
//! architecture from one host with no sysroot, because the runtime is freestanding, so every target
//! is buildable from any host. When no clang is available, krusty still builds — with no prebuilt
//! runtime, the native backend reports that plainly instead of failing somewhere inside a link.

use std::io::ErrorKind;
use std::path::{Path, PathBuf};
use std::process::Command;

// The supported targets, their triples, ELF machines and runtime flags. The compiler reads the same
// module, so the targets built here are the targets it names.
#[path = "src/native/target_contract.rs"]
mod target_contract;

/// Flags every target compiles with. The objects are embedded in krusty and linked into a user's
/// program, so their bytes must not depend on how the HOST's clang was configured: a distribution
/// that turns the stack protector on by default would otherwise leave `__stack_chk_fail` undefined
/// in a runtime nothing links a libc into, and unwind tables are data nothing reads.
const COMMON_FLAGS: &[&str] = &[
    "-std=c11",
    "-ffreestanding",
    "-nostdlib",
    "-fno-stack-protector",
    "-fno-asynchronous-unwind-tables",
    "-fno-unwind-tables",
    "-O2",
    "-c",
];

/// Flags for one runtime object, beyond [`COMMON_FLAGS`]. Linux stays non-PIC: the executable is
/// static and at a fixed address. The simulator dylib is slid by dyld, so its objects are
/// position-independent and do not use a small code model.
fn object_cflags(arch: target_contract::Arch, os: target_contract::Os) -> &'static [&'static str] {
    if os.static_elf() {
        arch.runtime_cflags()
    } else {
        &["-fPIC"]
    }
}

const SOURCES: &[&str] = &[
    "krusty_rt.c",
    "krusty_collections.c",
    "krusty_maps.c",
    "krusty_classes.c",
    "krusty_lang.c",
    "krusty_fp.c",
    "krusty_gc.c",
    "krusty_start.c",
];
const HEADERS: &[&str] = &["krusty_sys.h", "krusty_rt.h", "krusty_internal.h"];

fn main() {
    if let Err(error) = prebuild_runtime() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

fn prebuild_runtime() -> Result<(), String> {
    let runtime_dir = Path::new("src/native/runtime");
    for file in SOURCES.iter().chain(HEADERS) {
        println!(
            "cargo:rerun-if-changed={}",
            runtime_dir.join(file).display()
        );
    }
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/native/target_contract.rs");
    println!("cargo:rerun-if-env-changed=KRUSTY_RUNTIME_CC");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let compiler = std::env::var("KRUSTY_RUNTIME_CC").unwrap_or_else(|_| "clang".to_string());
    // Published to the crate, so a test that compiles against the runtime's headers asks the very
    // compiler that built the embedded runtime rather than resolving its own.
    println!("cargo:rustc-env=KRUSTY_RUNTIME_COMPILER={compiler}");

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs: the native runtime, prebuilt per target.\n");
    // `RuntimeObject` is the including module's `(file name, bytes)` pair.
    generated
        .push_str("pub const PREBUILT: &[(crate::native::NativeTarget, &[RuntimeObject])] = &[\n");

    let mut built_any = false;
    let mut compiler_missing = false;
    for (arch, os) in target_contract::SUPPORTED {
        let triple = target_contract::clang_triple(arch, os);
        let isa = target_contract::isa_triple(arch, os);
        // Every object is checked against the target it was asked for: a `KRUSTY_RUNTIME_CC`
        // wrapper that adds its own `--target` would otherwise file one architecture's code under
        // another's name without a single failed step. Linux objects are ELF; the simulator's are
        // Mach-O.
        // Filed under the whole target, not the architecture alone: two supported targets that
        // share an architecture must not share, or overwrite, one directory.
        let target_dir =
            out_dir
                .join("runtime")
                .join(format!("{}-{}", os.triple_name(), arch.triple_name()));
        std::fs::create_dir_all(&target_dir).expect("create runtime output directory");
        let mut objects = Vec::new();
        for source in SOURCES {
            let object = target_dir.join(Path::new(source).with_extension("o"));
            let status = Command::new(&compiler)
                .arg(format!("--target={triple}"))
                .args(COMMON_FLAGS)
                .args(object_cflags(arch, os))
                .arg("-I")
                .arg(runtime_dir)
                .arg("-o")
                .arg(&object)
                .arg(runtime_dir.join(source))
                .status();
            match status {
                Ok(status) if status.success() => {
                    if let Err(problem) = check_object(&object, arch, os) {
                        return Err(format!(
                            "native runtime: `{compiler}` built `{source}` for `{triple}` \
                             (codegen `{isa}`) as {problem}"
                        ));
                    }
                    objects.push(object)
                }
                Ok(status) => {
                    return Err(format!(
                        "native runtime: `{compiler}` failed compiling `{source}` for `{triple}` \
                         ({status})"
                    ));
                }
                Err(error) if error.kind() == ErrorKind::NotFound => {
                    println!(
                        "cargo:warning=native runtime: compiler `{compiler}` was not found; no native \
                         target will be available. Install clang, or set KRUSTY_RUNTIME_CC."
                    );
                    compiler_missing = true;
                    break;
                }
                Err(error) => {
                    return Err(format!(
                        "native runtime: cannot run compiler `{compiler}` for `{triple}` on `{source}`: \
                         {error}"
                    ));
                }
            }
        }
        // A compiler that cannot be started fails the same way for every target: one warning.
        if compiler_missing {
            break;
        }
        built_any = true;
        generated.push_str(&format!(
            "    (crate::native::NativeTarget::new(crate::native::Arch::{arch:?}, \
             crate::native::Os::{os:?}), &[\n"
        ));
        for object in &objects {
            let name = object.file_name().unwrap().to_string_lossy();
            generated.push_str(&format!(
                "        ({name:?}, include_bytes!({:?})),\n",
                object.display().to_string()
            ));
        }
        generated.push_str("    ]),\n");
    }
    generated.push_str("];\n");
    generated.push_str(&format!(
        "/// Whether any target's runtime was prebuilt (a C compiler was available when krusty was built).\n\
         pub const AVAILABLE: bool = {built_any};\n"
    ));
    generated.push_str(&format!(
        "/// The runtime sources every target's objects were compiled from, in the table's order. Only\n\
         /// the test that checks the table against them reads it.\n\
         #[cfg(test)]\n\
         pub const SOURCES: &[&str] = &{SOURCES:?};\n"
    ));
    std::fs::write(out_dir.join("prebuilt_runtime.rs"), generated)
        .expect("write prebuilt_runtime.rs");
    // With no compiler found, installing one is what should bring the runtime back, and that is a
    // change to `PATH`. Watched only then: a build that has its runtime must not rebuild the compiler
    // every time a shell with a different `PATH` runs cargo.
    if compiler_missing {
        println!("cargo:rerun-if-env-changed=PATH");
    }
    Ok(())
}

/// The identity of a freshly compiled object: a 64-bit little-endian relocatable for `arch` on
/// `os`, whose loaded sections ask for no more alignment than the link can give. `Err` names what
/// it is instead: an object the linker would refuse is a target that cannot link, and saying so
/// here names the cause where it arises rather than at every link.
fn check_object(
    object: &Path,
    arch: target_contract::Arch,
    os: target_contract::Os,
) -> Result<(), String> {
    let bytes = std::fs::read(object).map_err(|error| format!("an unreadable file ({error})"))?;
    if !os.static_elf() {
        return check_macho(&bytes);
    }
    let machine = arch.elf_machine();
    let max_page_size = arch.max_page_size();
    if bytes.len() < 20 || &bytes[..4] != b"\x7fELF" {
        return Err("something that is not ELF".to_string());
    }
    if bytes[4] != 2 || bytes[5] != 1 {
        return Err(format!(
            "ELF class {} / data encoding {}, not 64-bit little-endian",
            bytes[4], bytes[5]
        ));
    }
    let kind = u16::from_le_bytes([bytes[16], bytes[17]]);
    if kind != 1 {
        return Err(format!("ELF type {kind}, not a relocatable object"));
    }
    let found = u16::from_le_bytes([bytes[18], bytes[19]]);
    if found != machine {
        return Err(format!("code for ELF machine {found}, not {machine}"));
    }
    // A little-endian field of `width` bytes at `at`, read only if the file holds all of it.
    let field = |at: u64, width: usize| {
        usize::try_from(at)
            .ok()
            .and_then(|at| bytes.get(at..at.checked_add(width)?))
            .map(|field| {
                field
                    .iter()
                    .rev()
                    .fold(0u64, |value, byte| value << 8 | u64::from(*byte))
            })
            .ok_or_else(|| "an ELF object whose section headers are cut short".to_string())
    };
    const SHF_ALLOC: u64 = 2;
    let (table, entry_size, count) = (field(0x28, 8)?, field(0x3a, 2)?, field(0x3c, 2)?);
    for index in 0..count {
        let header = table.saturating_add(index * entry_size);
        let flags = field(header.saturating_add(0x08), 8)?;
        let align = field(header.saturating_add(0x30), 8)?;
        if flags & SHF_ALLOC != 0 && align > max_page_size {
            return Err(format!(
                "an object with a section aligned to {align:#x} bytes, more than the target's \
                 {max_page_size:#x}-byte maximum page size"
            ));
        }
    }
    Ok(())
}

/// A 64-bit little-endian Mach-O relocatable for arm64, which is what freestanding clang emits for
/// the iOS simulator without an SDK. Sections may not ask for more than a 16 KiB alignment: that
/// is the simulator's page size and the alignment the dylib's segments use.
fn check_macho(bytes: &[u8]) -> Result<(), String> {
    const MH_MAGIC_64: &[u8] = &[0xcf, 0xfa, 0xed, 0xfe];
    const CPU_TYPE_ARM64: u32 = 0x0100_000c;
    const MH_OBJECT: u32 = 1;
    const PAGE: u32 = 0x4000;
    if bytes.len() < 32 || &bytes[..4] != MH_MAGIC_64 {
        return Err("something that is not a 64-bit Mach-O object".to_string());
    }
    let u32_at = |at: usize| u32::from_le_bytes(bytes[at..at + 4].try_into().expect("four bytes"));
    let cputype = u32_at(4);
    if cputype != CPU_TYPE_ARM64 {
        return Err(format!("code for Mach-O cputype {cputype:#x}, not arm64"));
    }
    let kind = u32_at(12);
    if kind != MH_OBJECT {
        return Err(format!("Mach-O type {kind}, not a relocatable object"));
    }
    let ncmds = u32_at(16) as usize;
    let mut at = 32;
    for _ in 0..ncmds {
        if at + 8 > bytes.len() {
            return Err("a Mach-O object whose load commands are cut short".to_string());
        }
        let cmd = u32_at(at);
        let cmdsize = u32_at(at + 4) as usize;
        if cmdsize < 8 || at + cmdsize > bytes.len() {
            return Err("a Mach-O object whose load commands are cut short".to_string());
        }
        // LC_SEGMENT_64. The section alignment field is a power of two.
        if cmd == 0x19 {
            if cmdsize < 72 {
                return Err("a Mach-O segment command that is too small".to_string());
            }
            let nsects = u32_at(at + 64) as usize;
            let mut section = at + 72;
            for _ in 0..nsects {
                if section + 80 > at + cmdsize {
                    return Err("a Mach-O segment whose sections are cut short".to_string());
                }
                let align = u32_at(section + 52);
                if align < 32 && (1u32 << align) > PAGE {
                    return Err(format!(
                        "an object with a section aligned to {} bytes, more than the simulator's \
                         {PAGE:#x}-byte page",
                        1u32 << align
                    ));
                }
                section += 80;
            }
        }
        at += cmdsize;
    }
    Ok(())
}
