//! The KLIB krusty writes for a module, entry for entry against the one `kotlinc-native` writes.
//!
//! Each case under `tests/klib_writer_data/<case>/` is a module's sources and, under
//! `expected/<kotlin version>/`, the reference library's entries for that compiler release. The
//! comparison is two-sided: every reference entry must be written with the same bytes, and nothing
//! else may be written. Only the metadata half is compared yet: the reference's serialized IR
//! (`default/ir*`) is the IR writer's to produce, and is not part of the fixture.
//!
//! A reference is regenerated by compiling the case's sources, in file-name order, with the
//! matching Kotlin/Native distribution (`just kotlin-native <version>`):
//!
//! ```text
//! kotlinc-native -p library -o lib <case>/*.kt
//! unzip lib.klib 'default/manifest' 'default/linkdata/*' -d <case>/expected/<version>
//! ```

use std::path::{Path, PathBuf};

use krusty::diag::DiagSink;
use krusty::jvm::classpath::Classpath;
use krusty::klib::backend::KlibBackend;
use krusty::klib::write::KlibPlatform;
use krusty::source::SourceInput;

use crate::common;

fn case_dir(case: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/klib_writer_data")
        .join(case)
}

/// The library krusty writes for the case's sources, as (entry, bytes) in path order.
fn krusty_klib(case: &str) -> Vec<(String, Vec<u8>)> {
    let mut sources = std::fs::read_dir(case_dir(case))
        .expect("read the case directory")
        .map(|entry| entry.expect("read a case entry").path())
        .filter(|path| path.extension().is_some_and(|extension| extension == "kt"))
        .collect::<Vec<_>>();
    sources.sort();
    let texts = sources
        .iter()
        .map(|path| {
            let stem = path
                .file_stem()
                .expect("a source has a stem")
                .to_string_lossy()
                .into_owned();
            (stem, std::fs::read_to_string(path).expect("read a source"))
        })
        .collect::<Vec<_>>();
    let inputs = texts
        .iter()
        .map(|(stem, text)| SourceInput::kotlin(text).with_file_stem(stem))
        .collect::<Vec<_>>();
    let stems = texts
        .iter()
        .map(|(stem, _)| stem.clone())
        .collect::<Vec<_>>();
    let classpath = std::rc::Rc::new(Classpath::new(vec![
        common::stdlib_jar(),
        common::jdk_modules(),
    ]));
    let platform: Box<dyn krusty::libraries::SemanticPlatform> =
        Box::new(krusty::jvm::jvm_libraries::JvmLibraries::new(classpath).expect("JVM provider"));
    let features = krusty::conformance::test_features("", krusty::conformance::TestTarget::Native);
    let mut diags = DiagSink::new();
    let analysis = krusty::frontend::analyze_source_set_streaming_with_features(
        &inputs, platform, &features, &mut diags,
    );
    let backend = KlibBackend::new(
        KlibPlatform::Native {
            targets: vec!["linux_x64".to_string()],
        },
        vec!["stdlib".to_string()],
    );
    let entries = krusty::compiler::emit_analyzed(analysis, &stems, &backend, "lib", &mut diags);
    let messages = diags
        .diags
        .iter()
        .map(|diagnostic| diagnostic.msg.clone())
        .collect::<Vec<_>>();
    assert_eq!(messages, Vec::<String>::new(), "{case}: diagnostics");
    entries
}

/// The reference entries for the targeted Kotlin release, as (entry, bytes) in path order.
fn reference_klib(case: &str) -> Vec<(String, Vec<u8>)> {
    let root = case_dir(case)
        .join("expected")
        .join(krusty::kotlin_version::target().to_string());
    let mut entries = Vec::new();
    let mut pending = vec![root.clone()];
    while let Some(directory) = pending.pop() {
        for entry in std::fs::read_dir(&directory)
            .unwrap_or_else(|error| panic!("read {}: {error}", directory.display()))
        {
            let path = entry.expect("read a reference entry").path();
            if path.is_dir() {
                pending.push(path);
                continue;
            }
            let name = path
                .strip_prefix(&root)
                .expect("below the reference root")
                .to_string_lossy()
                .replace('\\', "/");
            entries.push((name, std::fs::read(&path).expect("read a reference entry")));
        }
    }
    entries.sort();
    entries
}

fn assert_case(case: &str) {
    let written = krusty_klib(case);
    let reference = reference_klib(case);
    let names = |entries: &[(String, Vec<u8>)]| {
        entries
            .iter()
            .map(|(name, _)| name.clone())
            .collect::<Vec<_>>()
    };
    assert_eq!(names(&written), names(&reference), "{case}: entries");
    for ((name, bytes), (_, expected)) in written.iter().zip(&reference) {
        assert!(
            bytes == expected,
            "{case}: {name} differs\n krusty: {bytes:02x?}\n kotlinc: {expected:02x?}"
        );
    }
}

/// Top-level functions and properties with what their records carry: visibility, default and
/// vararg parameters, inline and reified, suspend, tailrec, operator, infix, a contract,
/// `noinline`/`crossinline`, extension receivers, and `const val`s of every primitive kind. Three
/// files of one package, so the package's fragments are numbered.
#[test]
fn declarations_match_kotlinc_native() {
    assert_case("declarations");
}

/// Files of two packages, interleaved, and one in the root package: each package numbers its own
/// fragments, the root package writes `root_package/`, and the module header lists every package.
#[test]
fn packages_match_kotlinc_native() {
    assert_case("packages");
}

/// Typealiases (generic, internal, used in a signature), bounded and multiply bounded type
/// parameters, projections and stars, function types with receivers, and a generic extension
/// property.
#[test]
fn types_match_kotlinc_native() {
    assert_case("types");
}

/// A class is not written yet, and says so by name rather than producing a library without it.
#[test]
fn a_class_is_declined_by_name() {
    let classpath = std::rc::Rc::new(Classpath::new(vec![
        common::stdlib_jar(),
        common::jdk_modules(),
    ]));
    let platform: Box<dyn krusty::libraries::SemanticPlatform> =
        Box::new(krusty::jvm::jvm_libraries::JvmLibraries::new(classpath).expect("JVM provider"));
    let source = "package lib\nclass Box(val value: Int)\n";
    let inputs = [SourceInput::kotlin(source).with_file_stem("box")];
    let mut diags = DiagSink::new();
    let analysis = krusty::frontend::analyze_source_set_streaming_with_features(
        &inputs,
        platform,
        &krusty::conformance::test_features("", krusty::conformance::TestTarget::Native),
        &mut diags,
    );
    let backend = KlibBackend::new(
        KlibPlatform::Native {
            targets: vec!["linux_x64".to_string()],
        },
        vec!["stdlib".to_string()],
    );
    krusty::compiler::emit_analyzed(analysis, &["box".to_string()], &backend, "lib", &mut diags);
    let messages = diags
        .diags
        .iter()
        .map(|diagnostic| diagnostic.msg.clone())
        .collect::<Vec<_>>();
    assert_eq!(
        messages,
        vec!["krusty: the KLIB writer does not support classes yet".to_string()]
    );
}
