package demo

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*

annotation class Builder
annotation class Validate

/// A real KSP processor exercising the capability matrix, including MULTI-ROUND:
///   @Builder Foo      -> FooBuilder           (itself annotated @Validate)
///   @Validate Foo...  -> Foo...Validator      (only reachable if the generated builder is re-processed)
/// The @Validate handler firing proves KSP re-fed the round-1 generated file in a later round.
class BuilderProcessor(private val env: SymbolProcessorEnvironment) : SymbolProcessor {
    override fun process(resolver: Resolver): List<KSAnnotated> {
        // Capability: annotation query + declaration/property inspection + code generation.
        for (s in resolver.getSymbolsWithAnnotation("demo.Builder")) {
            if (s is KSClassDeclaration) {
                val pkg = s.packageName.asString()
                val name = s.simpleName.asString()
                val props = s.getAllProperties().map { it.simpleName.asString() }.toList()
                val out = env.codeGenerator.createNewFile(Dependencies(false), pkg, "${name}Builder")
                out.write("package $pkg\n".toByteArray())
                out.write("// generated by KSP from $name; properties=$props\n".toByteArray())
                out.write("@demo.Validate\n".toByteArray()) // re-triggers a later round
                out.write("class ${name}Builder\n".toByteArray())
                out.close()
            }
        }
        // Capability: MULTI-ROUND — fires only on the generated @Validate-annotated builder.
        for (s in resolver.getSymbolsWithAnnotation("demo.Validate")) {
            if (s is KSClassDeclaration) {
                val pkg = s.packageName.asString()
                val name = s.simpleName.asString()
                val out = env.codeGenerator.createNewFile(Dependencies(false), pkg, "${name}Validator")
                out.write("package $pkg\n".toByteArray())
                out.write("// generated in a later round from $name\n".toByteArray())
                out.write("class ${name}Validator\n".toByteArray())
                out.close()
            }
        }
        return emptyList()
    }
}

class BuilderProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        BuilderProcessor(environment)
}
