//! Catch clauses of a common-IR `try`, from source or generated by lowering.

use super::{ExprId, IrCatchBinding};
use crate::types::{Ty, TypeName};

/// One `catch (var: exc_internal) { body }` clause of an [`IrExpr::Try`].
#[derive(Clone, Debug)]
pub struct IrCatch {
    /// Value index the caught exception is bound to.
    pub var: u32,
    /// The debug-visible binding, absent for a compiler-generated handler — which binds no source
    /// name and must not appear in a local variable table.
    pub binding: Option<IrCatchBinding>,
    /// Semantic catch type. A reified type parameter stays a type parameter here so an inline
    /// call can substitute its argument before [`Self::exc_internal`] is read for emission.
    pub ty: Ty,
    /// JVM internal name of the caught exception type.
    pub exc_internal: TypeName,
    pub body: ExprId,
    /// The source line of the clause's `catch` keyword, marked at the handler's entry; absent for a
    /// compiler-generated handler, which has no clause of its own.
    pub line: Option<u32>,
}

impl IrCatch {
    /// A compiler-generated handler: no source clause, so neither a debug-visible binding nor a
    /// `catch` line.
    pub(crate) fn generated(var: u32, exc_internal: TypeName, body: ExprId) -> Self {
        Self {
            var,
            binding: None,
            ty: Ty::obj_name(exc_internal),
            exc_internal,
            body,
            line: None,
        }
    }

    /// The source spelling of the binding, absent for a compiler-generated handler.
    pub fn binding_name(&self) -> Option<&str> {
        self.binding.as_ref().map(|binding| binding.name.as_str())
    }
}
