//! Source lines a generated expression maps to only at one physical point rather than at its
//! start. Common lowering records the semantic fact once; a backend asks where the line belongs
//! instead of inferring it from a synthetic origin or expression shape.

use std::collections::{HashMap, HashSet};

use super::{ExprId, IrFile};

/// Where the `return` a `Unit` body is completed with takes its source line.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum UnitBodyExit {
    /// A block body falls off its closing `}` on this line (kotlinc's
    /// `setExtraLineNumberForVoidReturningFunction`), marked before the return materializes.
    ClosingBrace(u32),
    /// An expression body: fir2ir builds the return at the expression's end offset, so it carries
    /// this end line once the expression has run.
    ExpressionEnd(u32),
}

#[derive(Default)]
pub(super) struct GeneratedLineMarks {
    /// Implicit return identity → the expression body's closing source line.
    ///
    /// An explicit `return expression` keeps the call/return line already in effect. An
    /// expression-bodied callable instead maps its generated return instruction to the end of the
    /// body expression.
    implicit_return_ends: HashMap<ExprId, u32>,
    /// An inline template's implicit result expression -> the source line entered only after that
    /// expression evaluated successfully. A local return can bypass this point, so it belongs to
    /// the result itself rather than to the template's shared return join.
    evaluated_result_ends: HashMap<ExprId, u32>,
    /// Return a block body falls off its end into → the body's closing `}` line, which kotlinc's
    /// `setExtraLineNumberForVoidReturningFunction` marks BEFORE the returned value is loaded.
    fallthrough_returns: HashMap<ExprId, u32>,
    /// A `Unit` accessor body → the exit the `return` appended after it takes its line from.
    accessor_body_exits: HashMap<ExprId, UnitBodyExit>,
    /// Line a generated call enters only where it dispatches: its operands carry no source
    /// position of their own, so nothing marks the line at its start (a callable-reference
    /// carrier's `invoke`, whose stored receiver is read ahead of the call's line).
    dispatches: HashMap<ExprId, u32>,
    /// Expressions kotlinc builds without source offsets (an implicit context argument): no line
    /// begins at them, so a line marked where one starts has not begun yet.
    positionless: HashSet<ExprId>,
    /// Checked operations whose source line begins at their first generated operand. A property
    /// access owns its implicit context argument even though that argument has no source position.
    generated_operand_starts: HashSet<ExprId>,
    /// A function-value invocation generated by an inline declaration plan -> the caller line
    /// restored immediately before the erased `Object` result is adapted to its checked type.
    ///
    /// The invoke itself runs inside the inline expansion. Returning from that expansion enters
    /// the caller again at the result adaptation (`checkcast`/unbox), before a surrounding local
    /// declaration stores the value. This is a source/debug decision, not a JVM type inference:
    /// common lowering records the line and the JVM boundary chooses the physical adaptation.
    invocation_result_adaptations: HashMap<ExprId, u32>,
}

impl IrFile {
    pub(crate) fn mark_implicit_return_end_line(&mut self, returned: ExprId, line: u32) {
        self.generated_lines
            .implicit_return_ends
            .insert(returned, line);
    }

    pub(crate) fn implicit_return_end_line(&self, returned: ExprId) -> Option<u32> {
        self.generated_lines
            .implicit_return_ends
            .get(&returned)
            .copied()
    }

    pub(crate) fn mark_evaluated_result_end_line(&mut self, result: ExprId, line: u32) {
        self.generated_lines
            .evaluated_result_ends
            .insert(result, line);
    }

    pub(crate) fn evaluated_result_end_line(&self, result: ExprId) -> Option<u32> {
        self.generated_lines
            .evaluated_result_ends
            .get(&result)
            .copied()
    }

    pub(crate) fn mark_fallthrough_return_line(&mut self, returned: ExprId, line: u32) {
        self.generated_lines
            .fallthrough_returns
            .insert(returned, line);
    }

    pub(crate) fn fallthrough_return_line(&self, returned: ExprId) -> Option<u32> {
        self.generated_lines
            .fallthrough_returns
            .get(&returned)
            .copied()
    }

    /// Mark the line a `Unit` body's appended `return` carries.
    pub(crate) fn mark_unit_body_exit(&mut self, returned: ExprId, exit: UnitBodyExit) {
        match exit {
            UnitBodyExit::ClosingBrace(line) => self.mark_fallthrough_return_line(returned, line),
            UnitBodyExit::ExpressionEnd(line) => self.mark_implicit_return_end_line(returned, line),
        }
    }

    /// Record the exit of a `Unit` accessor body, before the accessor that appends its `return`
    /// exists.
    pub(crate) fn record_accessor_body_exit(&mut self, body: ExprId, exit: UnitBodyExit) {
        self.generated_lines.accessor_body_exits.insert(body, exit);
    }

    pub(crate) fn accessor_body_exit(&self, body: ExprId) -> Option<UnitBodyExit> {
        self.generated_lines.accessor_body_exits.get(&body).copied()
    }

    pub(crate) fn mark_dispatch_line(&mut self, call: ExprId, line: u32) {
        self.generated_lines.dispatches.insert(call, line);
    }

    pub(crate) fn dispatch_line(&self, call: ExprId) -> Option<u32> {
        self.generated_lines.dispatches.get(&call).copied()
    }

    pub(crate) fn mark_positionless(&mut self, expression: ExprId) {
        self.generated_lines.positionless.insert(expression);
    }

    pub(crate) fn is_positionless(&self, expression: ExprId) -> bool {
        self.generated_lines.positionless.contains(&expression)
    }

    pub(crate) fn mark_generated_operand_start(&mut self, expression: ExprId) {
        self.generated_lines
            .generated_operand_starts
            .insert(expression);
    }

    pub(crate) fn starts_at_generated_operand(&self, expression: ExprId) -> bool {
        self.generated_lines
            .generated_operand_starts
            .contains(&expression)
    }

    pub(crate) fn mark_invocation_result_adaptation(&mut self, expression: ExprId, line: u32) {
        self.generated_lines
            .invocation_result_adaptations
            .insert(expression, line);
    }

    pub(crate) fn invocation_result_adaptation_line(&self, expression: ExprId) -> Option<u32> {
        self.generated_lines
            .invocation_result_adaptations
            .get(&expression)
            .copied()
    }

    pub(crate) fn move_generated_operand_start(&mut self, source: ExprId, target: ExprId) {
        if self
            .generated_lines
            .generated_operand_starts
            .remove(&source)
        {
            self.generated_lines.generated_operand_starts.insert(target);
        }
    }

    /// Carry `source`'s generated line marks over to its copy `target`.
    pub(super) fn copy_generated_line_marks(&mut self, source: ExprId, target: ExprId) {
        let marks = &mut self.generated_lines;
        if let Some(&line) = marks.implicit_return_ends.get(&source) {
            marks.implicit_return_ends.insert(target, line);
        }
        if let Some(&line) = marks.evaluated_result_ends.get(&source) {
            marks.evaluated_result_ends.insert(target, line);
        }
        if let Some(&line) = marks.dispatches.get(&source) {
            marks.dispatches.insert(target, line);
        }
        if let Some(&line) = marks.fallthrough_returns.get(&source) {
            marks.fallthrough_returns.insert(target, line);
        }
        if marks.positionless.contains(&source) {
            marks.positionless.insert(target);
        }
        if marks.generated_operand_starts.contains(&source) {
            marks.generated_operand_starts.insert(target);
        }
        if let Some(&line) = marks.invocation_result_adaptations.get(&source) {
            marks.invocation_result_adaptations.insert(target, line);
        }
    }
}
